language: python

sudo: required

python:
  - "3.6"

services:
  - docker

install:
  - mv django.env.sample django.env
  - mv postgres.env.sample postgres.env
  - docker-compose pull
  - docker-compose build
  - pip install coverage
  - pip install codacy-coverage

script:
  - docker-compose run -e CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN --service-ports web sh init.sh python -m coverage run --source=api manage.py test

after_success:
  - python-codacy-coverage -r coverage.xml
