language: python

sudo: required

python:
  - "3.6"

services:
  - docker

install:
  - docker-compose pull
  - docker-compose build

script:
  - docker-compose run --no-deps --rm web python manage.py test