language: python

sudo: required

python:
  - "3.6"

services:
  - docker

install:
  - sed '/CLIENT/d' ./django.env.sample > ./django.env
  - sed -i '/TEST/d' ./django.env
  - sed -i 's/{DOMAIN}/chronoscio.auth0.com/g' ./django.env
  - sed -i 's#{IDENTIFIER}#https://chronoscio.org/api/#g' ./django.env
  - mv postgres.env.sample postgres.env
  - docker-compose pull
  - docker-compose build

script:
  - docker-compose run web black . --exclude /migrations/ --diff --check
  - docker-compose run -e CODACY_PROJECT_TOKEN -e AUTH0_CLIENT_SECRET -e AUTH0_CLIENT_ID --service-ports web sh init.sh python -m coverage run --source=api manage.py test

after_success:
  - python-codacy-coverage -r coverage.xml
