language: python

sudo: required

python:
  - "3.6"

services:
  - docker

install:
  - sed '/AUTH0_DOMAIN/d' ./django.env.sample > ./django.env
  - sed '/API_IDENTIFIER/d' ./django.env > ./django.env
  - sed '/TEST_ACCESS_TOKEN/d' ./django.env > ./django.env
  - mv postgres.env.sample postgres.env
  - docker-compose pull
  - docker-compose build

script:
  - docker-compose run -e CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN --service-ports web sh init.sh python -m coverage run --source=api manage.py test

after_success:
  - python-codacy-coverage -r coverage.xml
