language: python

sudo: required

python:
  - "3.6"

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d
  - docker ps -a

script:
  - docker-compose exec web python manage.py test