version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine #postgres:10-alpine    
    container_name: postgres01
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    image: nginx:1.13-alpine
    container_name: nginx01
    ports:
      - "80:80"
    volumes:
      - ./project:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: django01
    command: bash -c "bash .boot.sh" #bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn interactivemap.wsgi -b 0.0.0.0:80"
    depends_on:
      - db
    volumes:
      - ./project:/src
    expose:
      - "80"
    ports:
      - '3500:3500'
      - '8006:81'
    restart: always
