# Generated by Django 2.0.7 on 2018-07-17 04:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20)),
                ('local_name', models.CharField(max_length=30)),
                ('wikipedia', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('geo', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nation')),
            ],
        ),
    ]
