# Generated by Django 2.0.7 on 2018-07-20 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='api.Nation'),
        ),
    ]
