# Generated by Django 2.0.7 on 2018-09-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalterritory',
            name='political_entity',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='political_entity',
        ),
        migrations.AlterField(
            model_name='historicalpoliticalentity',
            name='url_id',
            field=models.SlugField(
                help_text='Identifier used to lookup Entities in the URL, should be kept short and must be unique',
                max_length=75),
        ),
        migrations.AlterField(
            model_name='politicalentity',
            name='url_id',
            field=models.SlugField(
                help_text='Identifier used to lookup Entities in the URL, should be kept short and must be unique',
                max_length=75,
                unique=True),
        ),
    ]
