# Generated by Django 2.0.7 on 2018-07-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180720_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territory',
            options={'verbose_name_plural': 'territories'},
        ),
    ]
