# Generated by Django 2.1.2 on 2018-10-11 02:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181004_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), default=[], help_text='Alternative names this state may be known by', size=None),
        ),
        migrations.AlterField(
            model_name='entity',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), default=[], help_text='Alternative names this state may be known by', size=None),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='historicalpoliticalentity',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), default=[], help_text='Alternative names this state may be known by', size=None),
        ),
        migrations.AlterField(
            model_name='historicalpoliticalentity',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None),
        ),
    ]
