# Generated by Django 2.0.7 on 2018-07-26 18:51

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180726_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaticRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalnation',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Color to display on map', max_length=18),
        ),
        migrations.AlterField(
            model_name='historicalnation',
            name='wikipedia',
            field=models.URLField(blank=True, help_text='Link to the Wikipedia article for this nation'),
        ),
        migrations.AlterField(
            model_name='historicalterritory',
            name='end_date',
            field=models.DateField(help_text='When this border ceases to exist'),
        ),
        migrations.AlterField(
            model_name='historicalterritory',
            name='geo',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='historicalterritory',
            name='start_date',
            field=models.DateField(help_text='When this border takes effect'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Color to display on map', max_length=18),
        ),
        migrations.AlterField(
            model_name='nation',
            name='wikipedia',
            field=models.URLField(blank=True, help_text='Link to the Wikipedia article for this nation'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='end_date',
            field=models.DateField(help_text='When this border ceases to exist'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='geo',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='territory',
            name='start_date',
            field=models.DateField(help_text='When this border takes effect'),
        ),
    ]
