# Generated by Django 2.0.7 on 2018-08-01 00:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180726_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnation',
            name='color',
            field=colorfield.fields.ColorField(db_index=True, default='#FF0000', help_text='Color to display on map', max_length=18),
        ),
        migrations.AlterField(
            model_name='nation',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Color to display on map', max_length=18, unique=True),
        ),
    ]
