# Generated by Django 2.0.7 on 2018-08-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180801_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territory',
            options={'verbose_name_plural': 'territories'},
        ),
        migrations.AlterField(
            model_name='historicalnation',
            name='name',
            field=models.CharField(db_index=True, help_text='Canonical name, should not include any epithets, must be unique', max_length=20),
        ),
        migrations.AlterField(
            model_name='nation',
            name='name',
            field=models.CharField(help_text='Canonical name, should not include any epithets, must be unique', max_length=20, unique=True),
        ),
    ]
