# Generated by Django 2.1.2 on 2018-10-23 18:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fix_migration_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalterritory',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='territory',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
