# Generated by Django 2.0.7 on 2018-08-08 05:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180801_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnation',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, help_text='CSV of alternative names this state may be known by', size=None),
        ),
        migrations.AlterField(
            model_name='historicalnation',
            name='name',
            field=models.TextField(db_index=True, help_text='Canonical name, should not include any epithets, must be unique', max_length=100),
        ),
        migrations.AlterField(
            model_name='nation',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, help_text='CSV of alternative names this state may be known by', size=None),
        ),
        migrations.AlterField(
            model_name='nation',
            name='name',
            field=models.TextField(help_text='Canonical name, should not include any epithets, must be unique', max_length=100, unique=True),
        ),
    ]
