# Generated by Django 2.1.2 on 2018-10-25 02:48

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181023_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalterritory',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, default=GEOSGeometry('{"type": "MultiPolygon","coordinates": [[[ [102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0] ]],[[ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ],[ [100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2] ]]]}'), srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='territory',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, default=GEOSGeometry('{"type": "MultiPolygon","coordinates": [[[ [102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0] ]],[[ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ],[ [100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2] ]]]}'), srid=4326),
            preserve_default=False,
        ),
    ]
