# Generated by Django 2.0.7 on 2018-08-09 02:42

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180808_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalterritory',
            name='control_type',
            field=models.TextField(choices=[('CC', 'Complete Control'), ('DT', 'Disputed Territory')], default='CC', max_length=2),
        ),
        migrations.AddField(
            model_name='territory',
            name='control_type',
            field=models.TextField(choices=[('CC', 'Complete Control'), ('DT', 'Disputed Territory')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalnation',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, help_text='Alternative names this state may be known by', size=None),
        ),
        migrations.AlterField(
            model_name='historicalterritory',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name='nation',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, help_text='Alternative names this state may be known by', size=None),
        ),
        migrations.AlterField(
            model_name='territory',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
