# Generated by Django 2.0.7 on 2018-08-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180809_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnation',
            name='url_id',
            field=models.SlugField(default='nation_default', help_text='Identifier used to lookup nations in the URL, should be kept short and must be unique', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nation',
            name='url_id',
            field=models.SlugField(default='nation_default1', help_text='Identifier used to lookup nations in the URL, should be kept short and must be unique', max_length=75, unique=True),
            preserve_default=False,
        ),
    ]
