# Generated by Django 2.0.7 on 2018-08-14 03:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180810_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalterritory',
            name='control_type',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='control_type',
        ),
        migrations.AddField(
            model_name='historicalnation',
            name='control_type',
            field=models.TextField(choices=[('CC', 'Complete Control'), ('DT', 'Disputed Territory')], default='CC', max_length=2),
        ),
        migrations.AddField(
            model_name='nation',
            name='control_type',
            field=models.TextField(choices=[('CC', 'Complete Control'), ('DT', 'Disputed Territory')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalnation',
            name='color',
            field=colorfield.fields.ColorField(db_index=True, help_text='Color to display on map', max_length=18),
        ),
        migrations.AlterField(
            model_name='nation',
            name='color',
            field=colorfield.fields.ColorField(help_text='Color to display on map', max_length=18, unique=True),
        ),
    ]
