# Generated by Django 2.0.7 on 2018-09-11 05:18

import colorfield.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180903_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaticrelation',
            name='diplo_type',
            field=models.TextField(choices=[('A', 'Military Alliance'), ('D', 'Dual Monarchy'), ('M', 'Condominium'), ('T', 'Trade League'), ('W', 'At War'), ('P', 'State or Province'), ('CP', 'Client State - Puppet State'), ('CV', 'Client State - Vassal State'), ('CPU', 'Client State - Personal Union'), ('CCR', 'Client State - Colony - Royal'), ('CCP', 'Client State - Colony - Propreitary'), ('CCC', 'Client State - Colony - Charter')], max_length=3),
        ),
        migrations.AlterField(
            model_name='historicaldiplomaticrelation',
            name='diplo_type',
            field=models.TextField(choices=[('A', 'Military Alliance'), ('D', 'Dual Monarchy'), ('M', 'Condominium'), ('T', 'Trade League'), ('W', 'At War'), ('P', 'State or Province'), ('CP', 'Client State - Puppet State'), ('CV', 'Client State - Vassal State'), ('CPU', 'Client State - Personal Union'), ('CCR', 'Client State - Colony - Royal'), ('CCP', 'Client State - Colony - Propreitary'), ('CCC', 'Client State - Colony - Charter')], max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalnation',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, default=[''], help_text='Alternative names this state may be known by', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalnation',
            name='color',
            field=colorfield.fields.ColorField(blank=True, db_index=True, help_text='Color to display on map', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnation',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=[''], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nation',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, default=[''], help_text='Alternative names this state may be known by', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nation',
            name='color',
            field=colorfield.fields.ColorField(blank=True, help_text='Color to display on map', max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=[''], size=None),
            preserve_default=False,
        ),
    ]
