# Generated by Django 2.0.7 on 2018-09-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180911_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplomaticrelation',
            name='first_party',
        ),
        migrations.RemoveField(
            model_name='diplomaticrelation',
            name='second_party',
        ),
        migrations.AddField(
            model_name='diplomaticrelation',
            name='child_party',
            field=models.ManyToManyField(related_name='child_parties', to='api.Nation'),
        ),
        migrations.AddField(
            model_name='diplomaticrelation',
            name='parent_party',
            field=models.ManyToManyField(related_name='parent_parties', to='api.Nation'),
        ),
    ]
