# Generated by Django 2.0.7 on 2018-10-08 22:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20181008_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnation',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nation',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
