# Generated by Django 2.0.7 on 2018-10-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181009_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnation',
            name='control_type',
            field=models.TextField(choices=[('CC', 'Complete Control'), ('DT', 'Disputed Territory')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='nation',
            name='control_type',
            field=models.TextField(choices=[('CC', 'Complete Control'), ('DT', 'Disputed Territory')], default='CC', max_length=2),
        ),
    ]
